substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: esp8266_dht22
  friendly_name: ESP8266 DHT22
  ip_address: !secret esp8266_dht22_ip


esphome:
  # https://esphome.io/components/esphomeyaml
  name: ${device_name}
  platform: ESP8266
  board: d1_mini


wifi:
  # https://esphome.io/components/wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip_address}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1
    dns2: !secret wifi_dns2

    
# web_server:
#   port: 80
  # https://esphomelib.com/esphomeyaml/components/web_server.html


logger:
  # https://esphome.io/components/logger


api:
  # password: !secret esphome_api_password
  # https://esphome.io/components/api


ota:
  password: !secret esphome_ota_password
  # https://esphome.io/components/ota



sensor:
  - platform: dht
    # https://esphome.io/components/sensor/dht.html
    pin: D1   # GPIO5
    temperature:
      name: ${friendly_name} Temperature
      filters:
        - offset: -1.5
        - filter_nan:
        - heartbeat: 15s
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
            send_first_at: 1
        - lambda: return x * (9.0/5.0) + 32.0;  # convert Celsius to Fahrenheit
      unit_of_measurement: "°F"
      # icon: "mdi:thermometer"   # gets thermometer icon by default
      # accuracy_decimals: 1      # gets 1 decimal by default
    humidity:
      name: ${friendly_name} Humidity
      filters:
        - filter_nan:
        - heartbeat: 15s
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
            send_first_at: 1
      # icon: "mdi:water-percent" # gets water-percent icon by default
      accuracy_decimals: 1        # gets 0 decimals by default
    model: AM2302                 # dht22 (attached board w/3 pins)
    update_interval: 10s
